
// This file has been generated by the GUI designer. Do not modify.
namespace GTKFirst
{
	public partial class FixedWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTKFirst.FixedWindow
			this.Name = "GTKFirst.FixedWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("FixedWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
