
// This file has been generated by the GUI designer. Do not modify.
namespace GTKFirst
{
	public partial class AlignmentWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GTKFirst.AlignmentWindow
			this.Name = "GTKFirst.AlignmentWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("AlignmentWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
